### ISSUE TITLE
Unable to retrieve child table data with parent doc type data when using useFrappeGetDocList

### ISSUE THREAD

**Issue by Shanuka-98** [The-Commit-Company/frappe-react-sdk#24]
I'm facing an issue while fetching child table data using the useFrappeGetDocList hook with the parent document type data.

Currently, I can only retrieve child table data using useFrappeGetDoc. However, in my case, I need to use filters, which require the useFrappeGetDocList hook.

Is there a way to retrieve associated child table data and parent data simultaneously using the useFrappeGetDocList hook?

**Comment by nikkothari22** [comment]
Hi @Shanuka-98 

The library uses the [standard Frappe REST API for listing documents](https://frappeframework.com/docs/v14/user/en/api/rest#listing-documents) in `useFrappeGetDocList`. AFAIK, the API does not allow joins between parent and child doctypes. 

What we do and recommend you to do as well is to create a custom GET API in your app and then use `useFrappeGetCall` to fetch the data.

**Comment by Shanuka-98** [comment]
Hi @nikkothari22,

Thank you for sharing that information! It's helpful to know that the Frappe REST API does not support joins between parent and child doctypes in the useFrappeGetDocList hook.

I appreciate your recommendation,
Thanks
