### ISSUE TITLE
Add Support for NextJS framework

### ISSUE THREAD

**Issue by sourabhmandal** [The-Commit-Company/frappe-react-sdk#41]
Hi, I loved the SDK you guys have built. It's a very handy tool for building custom UI. However, I was wondering if we could add support for the NextJS framework.

I tried installing the same library as it is in nextJS. However, it throws an error during server rendering.
If you wish I can raise a PR for the same.

**Comment by nikkothari22** [comment]
Hi @sourabhmandal 

Thanks! 

The way this SDK is built though, it's meant to be used with client side apps (it uses SWR internally: https://swr.vercel.app/docs/with-nextjs). This means that you can use the library in all client components in NextJS.

For SSR, it's just better to use frappe-js-SDK on the server. This library uses that internally anyway. 

I would actually use both in conjunction with one another depending on the use-case.
