### ISSUE TITLE
Can we use redux toolkit / redux toolkit query with sdk ?

### ISSUE THREAD

**Issue by SameedHasan** [The-Commit-Company/frappe-react-sdk#42]
I just wanted to know if we can use RTK/RTK Query  with frappe react sdk instead of contexts in large scale applications ?

**Comment by nikkothari22** [comment]
The SDK uses useSWR internally, which handles the caching and revalidation. 

I haven't used RTK Query but I don't think you can use it with this SDK. If you want to build a library that uses RTK, you can do that by using Frappe-JS-SDK.
