### ISSUE TITLE
Sample app for React/React Native with frappe-react-sdk

### ISSUE THREAD

**Issue by asharamseervi** [The-Commit-Company/frappe-react-sdk#45]
Firstly, I wanted to express my gratitude for your hard work on the `frappe-react-sdk`. This SDK seems like an excellent solution or better to say, a ray of hope for those devs who willing to use **Frappe as a Backend** for React and React Native applications.

We have been diligently attempting to use this SDK with both React and React Native, but unfortunately, we have been unsuccessful so far, even with the first hook. I would be grateful if you could assist us in utilizing this SDK, and in exchange, we would be happy to contribute an example app, which could serve as a guide for other developers who would like to try this SDK.

By working together in this way, we could increase the adoption rate of `frappe-react-sdk`.

CC: @nikkothari22

**Comment by nikkothari22** [comment]
Hey @asharamseervi - thank you.

We have not used the SDK extensively in React Native, but use it everyday on React. Did you get a chance to see my livestream with Hussain on Build with Hussain? We went over the setup of a React app using Doppio. A sample app for that is available here: https://github.com/The-Commit-Company/expense-tracker

If you have any specific issue, please feel free to post it here.
