### ISSUE TITLE
Error with CSRF token in logout

### ISSUE THREAD

**Issue by tsmanagers** [The-Commit-Company/frappe-react-sdk#46]
Hi,

I installed the Raven app in production mode but when I try to log out I am getting an error related to CSRF.

![csrf](https://github.com/The-Commit-Company/frappe-react-sdk/assets/108806672/68c28a0d-9339-416b-bcac-c92b85cb7838)

Thank ou for any help in advanced.

**Comment by nikkothari22** [comment]
Hey @tsmanagers - is this running on Frappe Cloud or on your local bench? Can you provide more information about your environment? Are you running a React server or is this running on the Frappe server at /raven? Is this the mobile app PWA or the web app?

**Comment by tsmanagers** [comment]
We are using self-hosted ERPNext version 14 on the Ubuntu server. 
Erpnext is running on https://erp.abc.com and React dashboard is running on https://erp.abc.com/dashboard

**Comment by nikkothari22** [comment]
You mentioned that you were having issues with Raven, but it seems like you have set up the React app using Doppio? 

If yes, then you need to check for the CSRF token and whether it's being passed in your network request (headers tab in the request details in inspector)
