### ISSUE TITLE
Customer Portal - React Redirect

### ISSUE THREAD

**Issue by tsmanagers** [The-Commit-Company/frappe-react-sdk#47]
We are developing a custom customer portal in React JS. Currently, customer is login into ERPNext then it will be redirected to the ERPNext customer portal; we wanted to redirect it to our custom portal. Can anyone help with how this can be done?

Through dropio app we can create new route like customer-portal but how we can integrate that route with ERPNext login feature so at the time of login our custom app will load instead of ERPNext customer portal

We are using ERPNext 14

**Comment by nikkothari22** [comment]
You can either set the home page of your site to the React app or add a redirect from / to the path on which your React app is hosted.

**Comment by tsmanagers** [comment]
Is there any way that we can redirect the customer's user from the normal ERPNext login page to our custom portal?
Basically user can do login from ERPNext login page and after login if its customer then it will redirect to our route if its system user then flow will be normal like it is there in ERPNext for desk access.

**Comment by nikkothari22** [comment]
I think you can achieve this using the default home page in your roles.

**Comment by tsmanagers** [comment]
Thank you very much Nikhil sir for your help & support.
