### ISSUE TITLE
How to avoid unnecessary API calls whenever React re-renders in frappe-react-sdk hooks

### ISSUE THREAD

**Issue by Shanuka-98** [The-Commit-Company/frappe-react-sdk#48]
Hello,

I'm seeking guidance on how to prevent unnecessary API calls triggered during React re-renders within frappe-react-sdk hooks. This issue arises due to the lack of conditional rendering support in React hooks. Specifically, I'm trying to avoid unnecessary API calls within the useFrappeGetDocList hook using conditional fetching. In my case, I have added a filter to the hook and I only want to fetch when that filter state changes. I wonder if there exists a feasible approach within frappe-react-sdk hooks or if it requires additional implementation?

**Comment by nikkothari22** [comment]
Hey @Shanuka-98 

Frappe React SDK uses useSWR internally and exposes all properties through it's hooks.

In your case, changing the filter will make a new API call and update the data. If you don't want to make any API call when there's no filter applied, you can pass `null` to the `key` prop. When there's a filter applied, just pass `undefined` as the key. 

You can read SWR's documentation for this. Frappe React SDK allows you to pass a key (pass null to not fetch, pass undefined to fetch, or pass a custom string for a custom key), and also allows you to pass SWR Configuration parameters as an object.

**Comment by Shanuka-98** [comment]
Here is a sample code, I just want to make a new API call only when `isPatternMatch` is true.
Thanks!

`import { useFrappeGetDocList } from "frappe-react-sdk";

const useIsExistingCustomer = (contactNumber) => {
  const contactNumberPattern = /^0\d{9}$/;
  const isPatternMatch = contactNumberPattern.test(contactNumber);

  const { data: customerData } = useFrappeGetDocList("Customer", {
    filters: [
      ["disabled", "=", 0],
      ["customer_mobile", "=", contactNumber],
    ],
  });

  // return true if customer is existing else return false
  return customerData?.length > 0;
};
export default useIsExistingCustomer;
`

**Comment by nikkothari22** [comment]
The SWR Key can be set to `null` when isPatternMatch is not true. Otherwise, just pass undefined to use the standard key.
```
import { useFrappeGetDocList } from "frappe-react-sdk";

const useIsExistingCustomer = (contactNumber) => {
  const contactNumberPattern = /^0\d{9}$/;
  const isPatternMatch = contactNumberPattern.test(contactNumber);

  const { data: customerData } = useFrappeGetDocList("Customer", {
    filters: [
      ["disabled", "=", 0],
      ["customer_mobile", "=", contactNumber],
    ],
  }, isPatternMatch ? undefined: null);

  // return true if customer is existing else return false
  return customerData?.length > 0;
};
export default useIsExistingCustomer;
```

**Comment by Shanuka-98** [comment]
Thank you so much, @nikkothari22, for your invaluable help. I truly appreciate it! Your guidance has been incredibly helpful. Also, thanks for sharing that alternative method using frappe-js-sdk. Sometimes, direct method implementation offers flexibility for specific functionalities that might not be available through hooks. 
Thank you once again for your support!
