### ISSUE TITLE
Frappe Version 15 Support 

### ISSUE THREAD

**Issue by SameedHasan** [The-Commit-Company/frappe-react-sdk#57]
Frappe version 15 introduces various enhancements and features, and it would greatly benefit developers to have an updated SDK that aligns with these changes. I am reaching out to bring attention to this need and kindly request the development and release of an SDK compatible with Frappe version 15.

**Comment by nikkothari22** [comment]
@SameedHasan - all v15 features are supported by the SDK. The places where we are looking to improve the DX is the new API v2 that's been introduced in v15. We plan on adding new hooks for those soon. They will be added to frappe-js-sdk first and then used here. Thanks for creating the issue.
