### ISSUE TITLE
How do we implement session management and user registration ?

### ISSUE THREAD

**Issue by sravani612** [The-Commit-Company/frappe-react-sdk#59]

**Comment by nikkothari22** [comment]
Hey @sravani612 

Frappe manages session via cookies.

Here's a video about authenticating with Frappe React SDK:

https://youtu.be/1OBoMcoaaSg?si=nRwQnJHU1HFfOPje

**Comment by sravani612** [comment]
I watched the video, but I couldn't find any information on user registration. Could you please provide guidance on how to proceed with registering users?

**Comment by kossanah** [comment]
Users are created in Frappe admin or enable sign up for self registration on the portal

**Comment by nikkothari22** [comment]
> I watched the video, but I couldn't find any information on user registration. Could you please provide guidance on how to proceed with registering users?

You'll have to make a POST API call to the sign up API if you want a sign up page on your React app.

**Comment by sravani612** [comment]
Understood, thank you for the response

> > I watched the video, but I couldn't find any information on user registration. Could you please provide guidance on how to proceed with registering users?
> 
> You'll have to make a POST API call to the sign up API if you want a sign up page on your React app.

Understood, thank you for the response
