### ISSUE TITLE
createContext Error

### ISSUE THREAD

**Issue by tsmanagers** [The-Commit-Company/frappe-react-sdk#61]
We have Erpnext 15 set up, and we are trying to integrate this SDK with the following code, but we are getting the below error.
Will this SDK work with NextJS, or will it only work with ReactJS?

Also, we installed the webpack plugin, but it still has the same issue.

<img width="746" alt="image (1)" src="https://github.com/The-Commit-Company/frappe-react-sdk/assets/108806672/0aee8b87-e435-4f70-841c-138786419b67">

**Comment by nikkothari22** [comment]
@tsmanagers This SDK is only for the client. So you can use it in all your client components. For server side components, you can use frappe-JS-SDK
