### ISSUE TITLE
Permission error

### ISSUE THREAD

**Issue by rs-rethik** [The-Commit-Company/frappe-react-sdk#62]
I have encountering while rendering the data using useFrappeGetDocList
Error message: 
{exception: 'frappe.exceptions.PermissionError', exc_type: 'PermissionError', exc: '["Traceback (most recent call last):\\n  File \\"app…ssionError\\nfrappe.exceptions.PermissionError\\n"]', _server_messages: '["{\\"message\\": \\"User <strong>Guest</strong> does…nses Record</strong>\\", \\"title\\": \\"Message\\"}"]', _error_message: 'No permission for Expenses Record', …}

**Comment by Harish-Stanch** [comment]
@rs-rethik It seems like you followed the tut video on youtube, In your doctype below permissions add the guest user and save (only to check if it works). Then add the Login logic and use its authentication to fetch.

**Comment by rs-rethik** [comment]
> @rs-rethik It seems like you followed the tut video on youtube, In your doctype below permissions add the guest user and save (only to check if it works). Then add the Login logic and use its authentication to fetch.

Yeah bro thank you..,I already sorted this issue by adding the Guest role in permission role settings.

**Comment by rs-rethik** [comment]
This error is because of Permission Error because the request will send as Guest. For solving this add Guest role in permission role settings..
Hope this helps
