### ISSUE TITLE
Custom Desk Pages with React - ERPNext 15

### ISSUE THREAD

**Issue by tsmanagers** [The-Commit-Company/frappe-react-sdk#66]
Hello Team,

We are using ERPNext 15. We already have 35+ pages in the React application, which we need to migrate to the ERPNext custom app. Can anyone help me or guide me through adding React to custom Desk pages?

https://discuss.frappe.io/t/react-in-desk-pages-erpnext-15/123683

**Comment by nikkothari22** [comment]
The forum is the right place to ask such questions. Already replied there.
