### ISSUE TITLE
Can is library use in react native project?

### ISSUE THREAD

**Issue by frappeerpnext** [The-Commit-Company/frappe-react-sdk#73]
Hi,
Please let me know if this libray can use in react native or not

Thanks,

**Comment by nikkothari22** [comment]
Yes it can be used with React Native. You'll need to pass a custom SWR Config to FrappeProvider.

For Authentication, you'll need to implement OAuth with the Frappe site yourself and then use the Bearer token obtained and pass it to FrappeProvider. Cookie based Auth won't work on RN.

Refer: https://swr.vercel.app/docs/advanced/react-native
